### PR TITLE
fix: change usage of 100vh to 100%, change server to listen on sensible ports

### PR DESCRIPTION
**Pull request by brennanmcmicking**
Chrome on iOS reports the viewport pixels without the navbar so the calendar view was rendering weirdly. This fixes that.  Tested on my iPhone with chrome and safari.

### CODE REVIEW

**Comment by malcolmseyd** [comment]
I havent tested the UI change yet, but you might be interested in the "Viewport Units" section on [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units). Something like `svh` was specifically designed to ensure that the browser navbar won't cover the content.

**Comment by brennanmcmicking** [comment]
> I havent tested the UI change yet, but you might be interested in the "Viewport Units" section on [this page](https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Values_and_Units). Something like `svh` was specifically designed to ensure that the browser navbar won't cover the content.

I think the 100% approach is the semantically correct solution - we just want the `<html>` and `<body>` tags to take up the entire window whether that's the full screen or something else (like a non-maximized browser window). I'm sure `100svh` would accomplish the same thing (and I came across it when trying to figure out why this was causing problems on chrome) but I opted for the simpler approach.

`100svh` would be very useful if we wanted an element within the page to be 100% of the visible viewport height and also have content above/below it, but that's not the case here.

**Review by malcolmseyd — APPROVED** [review]
I see what you mean, LGTM then :+1:

**Comment by brennanmcmicking** [comment]
> I see what you mean, LGTM then :+1: 

I'm gonna decline this PR cause the changes are included in the next PR where I also fixed the build

**Pull request closed without merging**
